"""Generate rtl/recip_lut.vh: 512-entry x 24-bit reciprocal ROM content.

Deterministic (no randomness): entry idx holds round(2^24 / (1810 + idx)),
identical to sensors.windows.reciprocal_lut_inv(m, m_min=1810, out_bits=24).
Indices 0..420 cover the supported M range [1810, 2230]; indices 421..511
(M = 2231..2321) are filled by the same formula but never addressed by a
valid window (power_calc forces outputs to 0 when invalid).

Regenerate: uv run python sim/gen_recip_lut.py  (then re-run the LUT tests)
"""

from fractions import Fraction
from pathlib import Path

M_MIN = 1810
DEPTH = 512
OUT_BITS = 24

repo = Path(__file__).resolve().parents[1]
out_path = repo / "rtl" / "recip_lut.vh"


def main() -> None:
    lines = [
        "// AUTO-GENERATED by sim/gen_recip_lut.py — do not hand-edit.",
        f"// ROM content: entry idx = round(2^{OUT_BITS} / ({M_MIN} + idx)), 24-bit.",
        f"// Covers M in [{M_MIN}, {M_MIN + DEPTH - 1}]; supported window range",
        "// [1810, 2230] uses indices 0..420.",
        "case (lut_idx)",
    ]
    for idx in range(DEPTH):
        m = M_MIN + idx
        # Exact rational check: no M in range yields an exact .5 fraction,
        # so Python banker's round == round-half-up == the RTL (P + M/2)/M.
        f = Fraction(1 << OUT_BITS, m)
        frac = f - int(f)
        assert frac != Fraction(1, 2), f"exact half at M={m}: rounding ambiguous"
        val = int(round(float(1 << OUT_BITS) / m))
        assert val == (int(f) if frac < Fraction(1, 2) else int(f) + 1), f"round mismatch M={m}"
        assert 0 <= val < (1 << 24), f"width overflow M={m}"
        lines.append(f"  9'd{idx}: lut_val = 24'd{val};")
    lines.append("  default: lut_val = 24'd0;")
    lines.append("endcase")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({DEPTH} entries)")


if __name__ == "__main__":
    main()
